###
# register user
POST /user/register HTTP/1.1
Host: localhost:9090
Content-Type: application/json

{
  "userEmail": "one@dooray.com",
  "userId": "user1",
  "userPw": "1111"
}

###
# select allUserId
GET http://localhost:9090/user/all
Accept: application/json

###
# select user
GET http://localhost:9090/user/user1
Accept: application/json